#################################################################################
# App variables
#################################################################################
my:
  db:
    schema: MyVideos93
    
#################################################################################
# Spring
#################################################################################
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.168.0.174:3306/${my.db.schema}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: xbmc
    password: xbmc
    driver-class-name: com.mysql.jdbc.Driver
    
#################################################################################
# Server
#################################################################################
server:
  port: 8080
  servlet-path: /
  
#################################################################################
#Logging
#################################################################################
logging:
  file: logs/kodiservice.log
#  pattern:
#    file: %d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%t] %c{1} - %msg%n
  level:
    root: INFO
    dk:
      leknoi:
        kodiservice: DEBUG
#    logging.level.com.example.devops=INFO
  
#################################################################################
# actuator
#################################################################################
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management:
  security:
    enabled: false
endpoints:
  sensitive: false