#################################################################################
# App variables
#################################################################################
my:
  db:
    schema: MyVideos93
    
#################################################################################
# Spring
#################################################################################
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.168.0.174:3306/${my.db.schema}
    username: xbmc
    password: xbmc
    driver-class-name: com.mysql.jdbc.Driver
    
#################################################################################
# Server
#################################################################################
server:
  port: 8082
  servlet-path: /
  
#################################################################################
#Logging
#################################################################################
logging:
  file: kodiservice.log
  
#################################################################################
# actuator
#################################################################################
management:
  security:
    enabled: false
endpoints:
  sensitive: false